version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command: >
      -c "sed -i 's/scram-sha-256/md5/' /var/lib/postgresql/data/pg_hba.conf"
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data